package ui;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.ProductBacklog;
import model.Resource;
import model.Sprint;
import model.UserStory;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Eric
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listPanel = new javax.swing.JPanel();
        listScroll = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        buttonPanel = new javax.swing.JPanel();
        addStoryButton = new javax.swing.JButton();
        removeStoryButton = new javax.swing.JButton();
        AddResource = new javax.swing.JButton();
        RemoveResourceButton = new javax.swing.JButton();
        descriptionPanel = new javax.swing.JPanel();
        descriptionScroll = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_resources = new javax.swing.JList<String>();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        closeItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        addSprint = new javax.swing.JMenuItem();
        openSprint = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        addToSprint = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenScrum");

        listPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        listScroll.setViewportView(list);

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listScroll)
                .addContainerGap())
        );

        buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        addStoryButton.setText("Add Story");
        addStoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStoryButtonActionPerformed(evt);
            }
        });

        removeStoryButton.setText("Remove Story");
        removeStoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStoryButtonActionPerformed(evt);
            }
        });

        AddResource.setText("Add Resource");
        AddResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddResourceActionPerformed(evt);
            }
        });

        RemoveResourceButton.setText("Remove Resource");
        RemoveResourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveResourceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStoryButton)
                    .addComponent(removeStoryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddResource)
                    .addComponent(RemoveResourceButton))
                .addGap(63, 63, 63))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStoryButton)
                    .addComponent(AddResource))
                .addGap(18, 18, 18)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeStoryButton)
                    .addComponent(RemoveResourceButton))
                .addContainerGap())
        );

        descriptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionScroll.setViewportView(descriptionTextArea);

        jTextField1.setEditable(false);

        jLabel1.setText("Estimation");

        list_resources.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resources", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jScrollPane1.setViewportView(list_resources);

        javax.swing.GroupLayout descriptionPanelLayout = new javax.swing.GroupLayout(descriptionPanel);
        descriptionPanel.setLayout(descriptionPanelLayout);
        descriptionPanelLayout.setHorizontalGroup(
            descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(descriptionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        descriptionPanelLayout.setVerticalGroup(
            descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        menu.setText("File");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        closeItem.setText("Close");
        menu.add(closeItem);

        menuBar.add(menu);

        jMenu1.setText("Sprint");

        addSprint.setText("Add Sprint");
        addSprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSprintActionPerformed(evt);
            }
        });
        jMenu1.add(addSprint);

        openSprint.setText("Open Sprint");
        openSprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSprintActionPerformed(evt);
            }
        });
        jMenu1.add(openSprint);
        jMenu1.add(jSeparator1);

        addToSprint.setText("Add Story to Sprint");
        addToSprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToSprintActionPerformed(evt);
            }
        });
        jMenu1.add(addToSprint);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStoryButtonActionPerformed
        AddStoryFrame addStoryFrame = new AddStoryFrame();
        addStoryFrame.setVisible(true);
    }//GEN-LAST:event_addStoryButtonActionPerformed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        UserStory story = (UserStory) list.getSelectedValue();
        String description = "";
        if (story != null) {
            description = story.getDescription();
            jTextField1.setText(story.getEstimation() + "");
            refreshList2();
        }
        descriptionTextArea.setText(description);
    }//GEN-LAST:event_listMouseClicked

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed

    }//GEN-LAST:event_menuActionPerformed

    private void removeStoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStoryButtonActionPerformed
        pb.remove((UserStory) list.getSelectedValue());
        refreshList();
        descriptionTextArea.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_removeStoryButtonActionPerformed

    private void AddResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddResourceActionPerformed
        if (list.getSelectedIndex() != -1) {
            AddResourcesFrame addResources = new AddResourcesFrame();
            addResources.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_AddResourceActionPerformed

    private void RemoveResourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveResourceButtonActionPerformed
        removeResource();
        refreshList2();
    }//GEN-LAST:event_RemoveResourceButtonActionPerformed

    private void addSprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSprintActionPerformed
        sprints.add(new Sprint());
    }//GEN-LAST:event_addSprintActionPerformed

    private void openSprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSprintActionPerformed
        Sprint result = (Sprint) JOptionPane.showInputDialog(null,
                "Choose a Sprint",
                "Open Sprint",
                JOptionPane.QUESTION_MESSAGE,
                null,
                sprints.toArray(),
                sprints.get(0));
        if (result != null){
            new SprintFrame(result).setVisible(true);
        }
    }//GEN-LAST:event_openSprintActionPerformed

    private void addToSprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToSprintActionPerformed
        if (list.getSelectedIndex() != -1) {
            Sprint result = (Sprint) JOptionPane.showInputDialog(null,
                    "Choose a Sprint",
                    "Add Story to Sprint",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    sprints.toArray(),
                    sprints.get(0));
            if (result != null) {
                result.insertStory((UserStory) list.getSelectedValue());
            }
            
        }
    }//GEN-LAST:event_addToSprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddResource;
    private javax.swing.JButton RemoveResourceButton;
    private javax.swing.JMenuItem addSprint;
    private javax.swing.JButton addStoryButton;
    private javax.swing.JMenuItem addToSprint;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JMenuItem closeItem;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JScrollPane descriptionScroll;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JList list;
    private javax.swing.JPanel listPanel;
    private javax.swing.JScrollPane listScroll;
    public static javax.swing.JList<String> list_resources;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openSprint;
    private javax.swing.JButton removeStoryButton;
    // End of variables declaration//GEN-END:variables
    public static ProductBacklog pb = new ProductBacklog();
    private static DefaultListModel model;
    private static DefaultListModel model2;
    private static ArrayList<Sprint> sprints = new ArrayList<>();

    public static void refreshList() {
        model = new DefaultListModel();
        ArrayList<UserStory> backlog = pb.getBacklog();
        for (UserStory story : backlog) {
            model.addElement(story);
        }
        list.setModel(model);
    }

    public static void refreshList2() {
        UserStory story = (UserStory) list.getSelectedValue();
        if (story != null) {
            model2 = new DefaultListModel();
            ArrayList<Resource> resource = story.getResources();
            for (Resource r : resource) {
                model2.addElement(r.GetName());
            }
            list_resources.setModel(model2);
        }
    }

    public static void removeResource() {
        int story_index = list_resources.getSelectedIndex();
        int resource_index = list.getSelectedIndex();
        if ((story_index != -1) && (resource_index != -1)) {
            pb.getBacklog().get(resource_index).getResources().remove(story_index);
        }
    }
}
